config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'skills/index'
  resources :employees
  resources :vacancies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_and_belongs_to_many :skills
  include ContactInfoHelper
  validates_format_of :name,
                      :with => /\A[а-яА-яёЁ]*\s*[а-яА-яёЁ]*\s*[а-яА-яёЁ]*\s*\z/,
                      message: 'Имя должно содержать 3 слова из кирилических букв и пробелов'
  validates :email,
            format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i},
            allow_blank: true
  validate :validate_if_have_any_contact
  scope :all_active, -> { where(status: true).order(desired_salary: :asc) }
  attr_accessor :skills_list
  attr_accessor :skills_rank

  def status_name
    status ? 'ищет' : 'занят'
  end

  def skills_list=(desired_skills)
    skills_to_add =[]
    desired_skills.split(',').each do |s|
      skills_to_add << (Skill.find_by_id(s) || Skill.find_or_create_by(name: s))
    end
    skills.delete(skills-skills_to_add)
    skills << (skills_to_add-skills)
  end

  def vacancies
    vacancies=Vacancy.all_active.joins(:skills).where("skill_id in (?)", skills.map(&:id)).distinct
    vacancies.each do |v|
      v.skills_rank=((v.skills & skills).count*1.0 / v.skills.count)
    end
    return vacancies
  end

  private

  def validate_if_have_any_contact
    if phone_number.blank? and email.blank?
      errors.add(:contact_info, "Необходимо заполнить поле номер телефона или адрес электронной почты")
    end
  end

end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name, :uniqueness => true
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  has_and_belongs_to_many :skills, :join_table => 'vacancies_skills'
  include ContactInfoHelper
  scope :all_active, -> { where("? between start_date and end_date", Time.current).order(salary: :desc) }
  attr_accessor :skills_list
  attr_accessor :skills_rank

  def skills_list=(desired_skills)
    skills_to_add =[]
    desired_skills.split(',').each do |s|
      skills_to_add << (Skill.find_by_id(s) || Skill.find_or_create_by(name: s))
    end
    skills.delete(skills-skills_to_add)
    skills << (skills_to_add-skills)
  end

  def employees
    employees=Employee.all_active.joins(:skills).where("skill_id in (?)", skills.map(&:id)).distinct
    employees.each do |v|
      v.skills_rank=((v.skills & skills).count*1.0 / skills.count)
    end
    return employees
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:name, :status, :desired_salary, :skills_list, :phone_number, :email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @employees=Employee.all_active
    @vacancies=Vacancy.all_active
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills=Skill.where("name like ?", "#{params['q']}%")
    respond_to do |format|
      format.json { render :json => @skills }
    end
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]

  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: 'Vacancy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vacancy_params
    params.require(:vacancy).permit(:name, :start_date, :end_date, :salary, :skills_list, :phone_number, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_info_helper.rb
module ContactInfoHelper
  def phone_number_formatter
    return 'не предоставлен' if phone_number.nil?
    if phone_number.scan(/\d/).count==11
      phone_number.gsub!(/[\s+\(\)]/, '')
      "+#{phone_number[0]}"+
          "(#{phone_number[1..3]})"+
          "#{phone_number[4..6]}-"+
          "#{phone_number[7..8]}-"+
          "#{phone_number[9..10]}"
    else
      phone_number
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/contact_info/_contact.html.erb
<p>
  <strong>Телефон:</strong>
  <%= contacts[:phone_number_formatter] %>
</p>

<p>
  <strong>Email:</strong>
  <%= contacts[:email].empty? ? 'не предоставлен' : mail_to(contacts[:email], contacts[:email]) %>
</p>

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
    <% if employee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

          <ul>
            <% employee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name, 'Фамилия, Имя, Отчество' %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :status, 'Статус поиска (при заполнении: в поиске)' %>
      <%= f.check_box :status %>
    </div>

    <div class="field">
      <%= f.label :desired_salary, 'Желаемая зарплата' %>
      <%= f.text_field :desired_salary %>
    </div>

    <div class="form-group">
      <%= f.label :contact_info, 'Контактная информация' %>
    <div class="field">
      <%= f.label :phone_number, 'Номер телефона' %>
      <%= f.text_field :phone_number %>
    </div>

    <div class="field">
      <%= f.label :email, 'Адрес электронной почты' %>
      <%= f.text_field :email %>
    </div>
    </div>
    <div class="field">
      <%= f.label :skills_list, "Ваши умения: (разделяйте их запятыми)" %><br/>
      <%= f.text_field :skills_list, data: {load: @employee.skills.map(&:attributes).to_json} %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить' %>
    </div>
<% end %>

app/views/employees/_list.html.erb
<% if employees.any? %>
    <table class="table table-stripped">
      <thead>
      <tr>
        <th>Имя</th>
        <th>Статус</th>
        <th>Желаемая зарплата</th>
        <% if control_actions %>
            <th colspan="2"></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% employees.each do |employee| %>
          <tr>
            <td><%= link_to employee.name, employee %></td>
            <td><%= employee.status_name %></td>
            <td><%= employee.desired_salary %></td>
            <% if control_actions %>
                <td><%= link_to 'Редактировать', edit_employee_path(employee) %></td>
                <td><%= link_to 'Удалить', employee, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <p>Работников не найдено</p>
<% end %>

app/views/employees/edit.html.erb
<h1>Редактирование работника</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Показать', @employee %> |
<%= link_to 'Назад', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Кадры</h1>

<%= render partial: "employees/list", locals: {employees: @employees, control_actions: true} %>

<br>

<%= link_to 'Новый кадр', new_employee_path %>

app/views/employees/new.html.erb
<h1>Новый работник</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Назад', employees_path %>

app/views/employees/show.html.erb
<div class="col-lg-6">

<h1><%= @employee.name %></h1>

<p>
  <strong>Статус:</strong>
  <%= @employee.status_name %>
</p>

<p>
  <strong>Желаемая зарплата:</strong>
  <%= @employee.desired_salary %>
</p>

<p>
  <strong>Умения:</strong>
  <% @employee.skills.each do |s| %>
      <span class="label label-default"><%= s.name %></span>
  <% end %>
</p>
<%= render partial: "contact_info/contact", locals: {contacts: @employee.slice(:phone_number_formatter, :email)} %>
</div>
<div class="col-lg-6">
  <h2>Совпадающие вакансии</h2>
  <%= render partial: "vacancies/list", locals: {vacancies: @employee.vacancies.select { |v| v.skills_rank>=1.0 }, control_actions: false} %>
  <h2>Частично совпадающие вакансии</h2>
  <%= render partial: "vacancies/list", locals: {vacancies: @employee.vacancies.select { |v| v.skills_rank>=0.5 and v.skills_rank<1.0 }, control_actions: false} %>
</div>
<div class="col-lg-12">
<%= link_to 'Редактировать', edit_employee_path(@employee) %> |
<%= link_to 'Назад', employees_path %>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1>Кадры в поиске</h1>
    <%= render partial: "employees/list", locals: {employees: @employees, control_actions: false} %>
  </div>
  <div class="col-lg-6">
    <h1>Активные вакансии</h1>
    <%= render partial: "vacancies/list", locals: {vacancies: @vacancies, control_actions: false} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RecruitmentAgency" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'RecruitmentAgency', root_path, :class => 'navbar-brand' %>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Кадры', employees_path %></li>
          <li><%= link_to "Вакансии", vacancies_path %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div><!--/row-->

    <footer>
      <p>&copy; Company 2016</p>
    </footer>

  </div> <!-- /container -->

  </body>
</html>

app/views/vacancies/_form.html.erb
<%= form_for(vacancy) do |f| %>
    <% if vacancy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

          <ul>
            <% vacancy.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name, 'Название компании' %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :start_date, 'Дата начала действия вакансии' %>
      <%= f.datetime_select :start_date %>
    </div>

    <div class="field">
      <%= f.label :end_date, 'Дата окончания действия вакансии' %>
      <%= f.datetime_select :end_date %>
    </div>

    <div class="field">
      <%= f.label :salary, 'Зарплата' %>
      <%= f.text_field :salary %>
    </div>

    <div class="field">
      <%= f.label :phone_number, 'Номер телефона' %>
      <%= f.text_field :phone_number %>
    </div>

    <div class="field">
      <%= f.label :email, 'Адрес электронной почты' %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :skills_list, "Необходимые умения: (разделяйте их запятыми)" %><br/>
      <%= f.text_field :skills_list, data: {load: @vacancy.skills.map(&:attributes).to_json} %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить' %>
    </div>
<% end %>

app/views/vacancies/_list.html.erb
<% if vacancies.any? %>
    <table class="table table-stripped">
      <thead>
      <tr>
        <th>Название</th>
        <th>С</th>
        <th>По</th>
        <th>Зарплата</th>
        <% if control_actions %>
            <th colspan="2"></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% vacancies.each do |vacancy| %>
          <tr>
            <td><%= link_to vacancy.name, vacancy %></td>
            <td><%= vacancy.start_date.strftime("%d.%m.%y") if vacancy.start_date %></td>
            <td><%= vacancy.end_date.strftime("%d.%m.%y") if vacancy.end_date %></td>
            <td><%= vacancy.salary %></td>
            <% if control_actions %>
                <td><%= link_to 'Изменить', edit_vacancy_path(vacancy) %></td>
                <td><%= link_to 'Удалить', vacancy, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <p>Вакансий не найдено</p>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Редактирование вакансии</h1>

<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Показать', @vacancy %> |
<%= link_to 'Назад', vacancies_path %>

app/views/vacancies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Все вакансии</h1>

<%= render partial: "vacancies/list", locals: {vacancies: @vacancies, control_actions: true} %>

<br>

<%= link_to 'Добавить новую вакансию', new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>Новая вакансия</h1>

<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Назад', vacancies_path %>

app/views/vacancies/show.html.erb
<div class="col-lg-6">

<h1><%= @vacancy.name %></h1>


<p>
  <strong>Начало поиска:</strong>
  <%= @vacancy.start_date.strftime("%d %B %Y") %>
</p>

<p>
  <strong>Конец поиска:</strong>
  <%= @vacancy.end_date.strftime("%d %B %Y") %>
</p>

<p>
  <strong>Зарплата:</strong>
  <%= @vacancy.salary %>
</p>

<p>
  <strong>Необходимые умения:</strong>
  <% @vacancy.skills.each do |s| %>
      <span class="label label-default"><%= s.name %></span>
  <% end %>
</p>

<%= render partial: "contact_info/contact", locals: {contacts: @vacancy.slice(:phone_number_formatter, :email)} %>
</div>
<div class="col-lg-6">
  <h2>Подходящие работники</h2>
  <%= render partial: "employees/list", locals: {employees: @vacancy.employees.select { |v| v.skills_rank>=1.0 }, control_actions: false} %>
  <h2>Частично подходящие кадры</h2>
  <%= render partial: "employees/list", locals: {employees: @vacancy.employees.select { |v| v.skills_rank>=0.5 and v.skills_rank<1.0 }, control_actions: false} %>
</div>
<div class="col-lg-12">


<%= link_to 'Изменить', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Назад', vacancies_path %>
</div>